build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest
codenotary:
  signer: codenotary@bog.dev
  base_image: notary@home-assistant.io
