name: plex_debrid
description: "Plex torrent streaming through Debrid Services"
version: "2.71-1"
slug: plex_debrid
init: false
arch:
  - aarch64
  - amd64
  - i386
map:
  - config:rw
ingress: true
image: "ghcr.io/bogsen/homeassistant-addon-plex_debrid-{arch}"
